---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-ip-hmrc-access-code
  name: pttg-ip-hmrc-access-code
spec:
  ports:
  - name: http
    port: 80
    targetPort: 10080
  - name: https
    port: 443
    targetPort: 10443
  selector:
    name: pttg-ip-hmrc-access-code
